org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.2.0

mod_id=estrella_magica_fugaz
mod_name=Estrella Magica Fugaz
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.estrellamagica.fugaz
mod_authors=TuNombre
mod_description=Estrellas fugaces de colores iluminan la noche. Algunas caen y dejan fragmentos estelares.
